version: '3.0'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.18
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - verretech
  gateway:
    build:
      context: .
      dockerfile: ./gateway/install/Dockerfile  
    ports:
      - "10000:10000"
    networks: 
      - verretech

  produit:
    build:
      context: .
      dockerfile: ./produit/install/Dockerfile
    ports:
      - "50051:50051" 
    networks: 
      - verretech  

  utilisateur:
    build:
      context: .
      dockerfile: ./utilisateur/install/Dockerfile
    ports:
      - "50052:50052"
    networks: 
      - verretech 

  panier:
    build:
      context: .
      dockerfile: ./panier/install/Dockerfile
    ports:
      - "50053:50053"
    networks: 
      - verretech

  commande:
    build:
      context: .
      dockerfile: ./commande/install/Dockerfile 
    ports:
      - "50054:50054"
    networks: 
      - verretech

  erp:
    build:
      context: .
      dockerfile: ./erp/install/Dockerfile    
    ports:
      - "50050:50050"
      - "50055:50055"
    networks: 
      - verretech

networks: 
  verretech:
    driver: bridge
 
