version: '3.0'

services:
  produit:
    build:
      context: .
      dockerfile: /produit/install/Dockerfile   

  utilisateur:
    build:
      context: .
      dockerfile: /utilisateur/install/Dockerfile   

  gateway:
    build:
      context: .
      dockerfile: /gateway/install/Dockerfile  
  
  erp:
    build:
      context: .
      dockerfile: /erp/install/Dockerfile   

  commande:
    build:
      context: .
      dockerfile: /commande/install/Dockerfile 
  
  panier:
    build:
      context: .
      dockerfile: /panier/install/Dockerfile   
