version: '3.0'

services:
  produit:
    build:
      context: /produit/install
      dockerfile: /home/ubuntu/verretech-microservices/produit/install/Dockerfile
  utilisateur:
    build:
      context: /utilisateur/install
      dockerfile: /home/ubuntu/verretech-microservices/utilisateur/install/Dockerfile
