version: '3.0'

services:
  produit:
    build:
      context: .
     dockerfile: /produit/install/Dockerfile   // Pour le local

  utilisateur:
    build:
      context: .
    dockerfile: /utulisateur/install/Dockerfile   // Pour le local

  gateway:
    build:
      context: .
     dockerfile: /gateway/install/Dockerfile   // Pour le local
  
  erp:
    build:
      context: .
    dockerfile: /erp/install/Dockerfile   // Pour le local

  commande:
    build:
      context: .
     dockerfile: /commande/install/Dockerfile   // Pour le local
  
  panier:
    build:
      context: .
     dockerfile: /panier/install/Dockerfile   // Pour le local
