// protoc --go_out=. --go-grpc_out=. ./proto/produit.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: proto/produit.proto

package produitpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Localisation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Adresse string `protobuf:"bytes,2,opt,name=adresse,proto3" json:"adresse,omitempty"`
	Ville   string `protobuf:"bytes,3,opt,name=ville,proto3" json:"ville,omitempty"`
	Cp      string `protobuf:"bytes,4,opt,name=cp,proto3" json:"cp,omitempty"`
}

func (x *Localisation) Reset() {
	*x = Localisation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_produit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Localisation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Localisation) ProtoMessage() {}

func (x *Localisation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_produit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Localisation.ProtoReflect.Descriptor instead.
func (*Localisation) Descriptor() ([]byte, []int) {
	return file_proto_produit_proto_rawDescGZIP(), []int{0}
}

func (x *Localisation) GetAdresse() string {
	if x != nil {
		return x.Adresse
	}
	return ""
}

func (x *Localisation) GetVille() string {
	if x != nil {
		return x.Ville
	}
	return ""
}

func (x *Localisation) GetCp() string {
	if x != nil {
		return x.Cp
	}
	return ""
}

type PointRetrait struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nom          string        `protobuf:"bytes,1,opt,name=nom,proto3" json:"nom,omitempty"`
	Localisation *Localisation `protobuf:"bytes,2,opt,name=localisation,proto3" json:"localisation,omitempty"`
}

func (x *PointRetrait) Reset() {
	*x = PointRetrait{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_produit_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PointRetrait) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointRetrait) ProtoMessage() {}

func (x *PointRetrait) ProtoReflect() protoreflect.Message {
	mi := &file_proto_produit_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointRetrait.ProtoReflect.Descriptor instead.
func (*PointRetrait) Descriptor() ([]byte, []int) {
	return file_proto_produit_proto_rawDescGZIP(), []int{1}
}

func (x *PointRetrait) GetNom() string {
	if x != nil {
		return x.Nom
	}
	return ""
}

func (x *PointRetrait) GetLocalisation() *Localisation {
	if x != nil {
		return x.Localisation
	}
	return nil
}

type Stock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PointRetrait *PointRetrait `protobuf:"bytes,1,opt,name=pointRetrait,proto3" json:"pointRetrait,omitempty"`
	Qte          int32         `protobuf:"varint,2,opt,name=qte,proto3" json:"qte,omitempty"`
}

func (x *Stock) Reset() {
	*x = Stock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_produit_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stock) ProtoMessage() {}

func (x *Stock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_produit_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stock.ProtoReflect.Descriptor instead.
func (*Stock) Descriptor() ([]byte, []int) {
	return file_proto_produit_proto_rawDescGZIP(), []int{2}
}

func (x *Stock) GetPointRetrait() *PointRetrait {
	if x != nil {
		return x.PointRetrait
	}
	return nil
}

func (x *Stock) GetQte() int32 {
	if x != nil {
		return x.Qte
	}
	return 0
}

type Photo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *Photo) Reset() {
	*x = Photo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_produit_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Photo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Photo) ProtoMessage() {}

func (x *Photo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_produit_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Photo.ProtoReflect.Descriptor instead.
func (*Photo) Descriptor() ([]byte, []int) {
	return file_proto_produit_proto_rawDescGZIP(), []int{3}
}

func (x *Photo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Produit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID          string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Ref         string   `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	Nom         string   `protobuf:"bytes,3,opt,name=nom,proto3" json:"nom,omitempty"`
	Description string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Prix        float32  `protobuf:"fixed32,5,opt,name=prix,proto3" json:"prix,omitempty"`
	Photos      []*Photo `protobuf:"bytes,6,rep,name=photos,proto3" json:"photos,omitempty"`
	Stocks      []*Stock `protobuf:"bytes,7,rep,name=stocks,proto3" json:"stocks,omitempty"`
	Tags        []string `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *Produit) Reset() {
	*x = Produit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_produit_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Produit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Produit) ProtoMessage() {}

func (x *Produit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_produit_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Produit.ProtoReflect.Descriptor instead.
func (*Produit) Descriptor() ([]byte, []int) {
	return file_proto_produit_proto_rawDescGZIP(), []int{4}
}

func (x *Produit) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Produit) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *Produit) GetNom() string {
	if x != nil {
		return x.Nom
	}
	return ""
}

func (x *Produit) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Produit) GetPrix() float32 {
	if x != nil {
		return x.Prix
	}
	return 0
}

func (x *Produit) GetPhotos() []*Photo {
	if x != nil {
		return x.Photos
	}
	return nil
}

func (x *Produit) GetStocks() []*Stock {
	if x != nil {
		return x.Stocks
	}
	return nil
}

func (x *Produit) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ListProduits struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Produits []*Produit `protobuf:"bytes,1,rep,name=produits,proto3" json:"produits,omitempty"`
}

func (x *ListProduits) Reset() {
	*x = ListProduits{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_produit_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListProduits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProduits) ProtoMessage() {}

func (x *ListProduits) ProtoReflect() protoreflect.Message {
	mi := &file_proto_produit_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProduits.ProtoReflect.Descriptor instead.
func (*ListProduits) Descriptor() ([]byte, []int) {
	return file_proto_produit_proto_rawDescGZIP(), []int{5}
}

func (x *ListProduits) GetProduits() []*Produit {
	if x != nil {
		return x.Produits
	}
	return nil
}

type ProduitsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Listproduits *ListProduits `protobuf:"bytes,1,opt,name=listproduits,proto3" json:"listproduits,omitempty"`
}

func (x *ProduitsRequest) Reset() {
	*x = ProduitsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_produit_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProduitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduitsRequest) ProtoMessage() {}

func (x *ProduitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_produit_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduitsRequest.ProtoReflect.Descriptor instead.
func (*ProduitsRequest) Descriptor() ([]byte, []int) {
	return file_proto_produit_proto_rawDescGZIP(), []int{6}
}

func (x *ProduitsRequest) GetListproduits() *ListProduits {
	if x != nil {
		return x.Listproduits
	}
	return nil
}

type ProduitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Produit *Produit `protobuf:"bytes,1,opt,name=produit,proto3" json:"produit,omitempty"`
}

func (x *ProduitRequest) Reset() {
	*x = ProduitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_produit_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProduitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduitRequest) ProtoMessage() {}

func (x *ProduitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_produit_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduitRequest.ProtoReflect.Descriptor instead.
func (*ProduitRequest) Descriptor() ([]byte, []int) {
	return file_proto_produit_proto_rawDescGZIP(), []int{7}
}

func (x *ProduitRequest) GetProduit() *Produit {
	if x != nil {
		return x.Produit
	}
	return nil
}

type GetAllProduitsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllProduitsRequest) Reset() {
	*x = GetAllProduitsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_produit_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllProduitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllProduitsRequest) ProtoMessage() {}

func (x *GetAllProduitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_produit_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllProduitsRequest.ProtoReflect.Descriptor instead.
func (*GetAllProduitsRequest) Descriptor() ([]byte, []int) {
	return file_proto_produit_proto_rawDescGZIP(), []int{8}
}

type ProduitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Produit *Produit `protobuf:"bytes,1,opt,name=produit,proto3" json:"produit,omitempty"`
}

func (x *ProduitResponse) Reset() {
	*x = ProduitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_produit_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProduitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduitResponse) ProtoMessage() {}

func (x *ProduitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_produit_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduitResponse.ProtoReflect.Descriptor instead.
func (*ProduitResponse) Descriptor() ([]byte, []int) {
	return file_proto_produit_proto_rawDescGZIP(), []int{9}
}

func (x *ProduitResponse) GetProduit() *Produit {
	if x != nil {
		return x.Produit
	}
	return nil
}

type ProduitsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Listproduits *ListProduits `protobuf:"bytes,1,opt,name=listproduits,proto3" json:"listproduits,omitempty"`
}

func (x *ProduitsResponse) Reset() {
	*x = ProduitsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_produit_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProduitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduitsResponse) ProtoMessage() {}

func (x *ProduitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_produit_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduitsResponse.ProtoReflect.Descriptor instead.
func (*ProduitsResponse) Descriptor() ([]byte, []int) {
	return file_proto_produit_proto_rawDescGZIP(), []int{10}
}

func (x *ProduitsResponse) GetListproduits() *ListProduits {
	if x != nil {
		return x.Listproduits
	}
	return nil
}

var File_proto_produit_proto protoreflect.FileDescriptor

var file_proto_produit_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x69, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x69, 0x74, 0x22, 0x4e,
	0x0a, 0x0c, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x69, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x69, 0x6c, 0x6c,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x69, 0x6c, 0x6c, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x63, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x63, 0x70, 0x22, 0x5b,
	0x0a, 0x0c, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x74, 0x72, 0x61, 0x69, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6e, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x6f, 0x6d,
	0x12, 0x39, 0x0a, 0x0c, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x69, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x69, 0x74,
	0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x69, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x6c,
	0x6f, 0x63, 0x61, 0x6c, 0x69, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x54, 0x0a, 0x05, 0x53,
	0x74, 0x6f, 0x63, 0x6b, 0x12, 0x39, 0x0a, 0x0c, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x74,
	0x72, 0x61, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x69, 0x74, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x74, 0x72, 0x61, 0x69,
	0x74, 0x52, 0x0c, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x74, 0x72, 0x61, 0x69, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x71, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x71, 0x74,
	0x65, 0x22, 0x19, 0x0a, 0x05, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0xd7, 0x01, 0x0a,
	0x07, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x69, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x66, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x65, 0x66, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x6f,
	0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x6f, 0x6d, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x72, 0x69, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x70, 0x72,
	0x69, 0x78, 0x12, 0x26, 0x0a, 0x06, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x73, 0x18, 0x06, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x69, 0x74, 0x2e, 0x50, 0x68, 0x6f,
	0x74, 0x6f, 0x52, 0x06, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x73, 0x12, 0x26, 0x0a, 0x06, 0x73, 0x74,
	0x6f, 0x63, 0x6b, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x69, 0x74, 0x2e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x06, 0x73, 0x74, 0x6f, 0x63,
	0x6b, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x22, 0x3c, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x69, 0x74, 0x73, 0x12, 0x2c, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x69,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x69, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x69, 0x74, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x69, 0x74, 0x73, 0x22, 0x4c, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x69, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x0c, 0x6c, 0x69, 0x73, 0x74, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x69, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x69, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x69, 0x74, 0x73, 0x52, 0x0c, 0x6c, 0x69, 0x73, 0x74, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x69,
	0x74, 0x73, 0x22, 0x3c, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x69, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x69, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x69, 0x74, 0x2e,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x69, 0x74, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x69, 0x74,
	0x22, 0x17, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x69,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3d, 0x0a, 0x0f, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x07,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x69, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x69, 0x74, 0x52,
	0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x69, 0x74, 0x22, 0x4d, 0x0a, 0x10, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x69, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x0c,
	0x6c, 0x69, 0x73, 0x74, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x69, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x69, 0x74, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x69, 0x74, 0x73, 0x52, 0x0c, 0x6c, 0x69, 0x73, 0x74, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x69, 0x74, 0x73, 0x32, 0xa2, 0x02, 0x0a, 0x0e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x69, 0x74, 0x12, 0x37, 0x0a, 0x0a, 0x41, 0x64,
	0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x69, 0x74, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x69, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x69, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x69, 0x74, 0x12, 0x45, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x69, 0x74, 0x73, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x69, 0x74, 0x2e,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x69, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x19, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x69, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x69,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x0e, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x69, 0x74, 0x73, 0x12, 0x1e, 0x2e, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x69, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x69, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x69, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x69, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x69, 0x74, 0x42, 0x79, 0x52, 0x65, 0x66, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x69, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x69, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x69, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x69, 0x74, 0x42, 0x15, 0x5a, 0x13,
	0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x69, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x69,
	0x74, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_produit_proto_rawDescOnce sync.Once
	file_proto_produit_proto_rawDescData = file_proto_produit_proto_rawDesc
)

func file_proto_produit_proto_rawDescGZIP() []byte {
	file_proto_produit_proto_rawDescOnce.Do(func() {
		file_proto_produit_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_produit_proto_rawDescData)
	})
	return file_proto_produit_proto_rawDescData
}

var file_proto_produit_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_produit_proto_goTypes = []interface{}{
	(*Localisation)(nil),          // 0: produit.Localisation
	(*PointRetrait)(nil),          // 1: produit.PointRetrait
	(*Stock)(nil),                 // 2: produit.Stock
	(*Photo)(nil),                 // 3: produit.Photo
	(*Produit)(nil),               // 4: produit.Produit
	(*ListProduits)(nil),          // 5: produit.ListProduits
	(*ProduitsRequest)(nil),       // 6: produit.ProduitsRequest
	(*ProduitRequest)(nil),        // 7: produit.ProduitRequest
	(*GetAllProduitsRequest)(nil), // 8: produit.GetAllProduitsRequest
	(*ProduitResponse)(nil),       // 9: produit.ProduitResponse
	(*ProduitsResponse)(nil),      // 10: produit.ProduitsResponse
}
var file_proto_produit_proto_depIdxs = []int32{
	0,  // 0: produit.PointRetrait.localisation:type_name -> produit.Localisation
	1,  // 1: produit.Stock.pointRetrait:type_name -> produit.PointRetrait
	3,  // 2: produit.Produit.photos:type_name -> produit.Photo
	2,  // 3: produit.Produit.stocks:type_name -> produit.Stock
	4,  // 4: produit.ListProduits.produits:type_name -> produit.Produit
	5,  // 5: produit.ProduitsRequest.listproduits:type_name -> produit.ListProduits
	4,  // 6: produit.ProduitRequest.produit:type_name -> produit.Produit
	4,  // 7: produit.ProduitResponse.produit:type_name -> produit.Produit
	5,  // 8: produit.ProduitsResponse.listproduits:type_name -> produit.ListProduits
	7,  // 9: produit.ServiceProduit.AddProduit:input_type -> produit.ProduitRequest
	6,  // 10: produit.ServiceProduit.UpdateProduits:input_type -> produit.ProduitsRequest
	8,  // 11: produit.ServiceProduit.GetAllProduits:input_type -> produit.GetAllProduitsRequest
	8,  // 12: produit.ServiceProduit.GetProduitByRef:input_type -> produit.GetAllProduitsRequest
	4,  // 13: produit.ServiceProduit.AddProduit:output_type -> produit.Produit
	10, // 14: produit.ServiceProduit.UpdateProduits:output_type -> produit.ProduitsResponse
	10, // 15: produit.ServiceProduit.GetAllProduits:output_type -> produit.ProduitsResponse
	4,  // 16: produit.ServiceProduit.GetProduitByRef:output_type -> produit.Produit
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_produit_proto_init() }
func file_proto_produit_proto_init() {
	if File_proto_produit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_produit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Localisation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_produit_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PointRetrait); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_produit_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_produit_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Photo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_produit_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Produit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_produit_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListProduits); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_produit_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProduitsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_produit_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProduitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_produit_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllProduitsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_produit_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProduitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_produit_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProduitsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_produit_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_produit_proto_goTypes,
		DependencyIndexes: file_proto_produit_proto_depIdxs,
		MessageInfos:      file_proto_produit_proto_msgTypes,
	}.Build()
	File_proto_produit_proto = out.File
	file_proto_produit_proto_rawDesc = nil
	file_proto_produit_proto_goTypes = nil
	file_proto_produit_proto_depIdxs = nil
}
