// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: proto/commande.proto

package commandepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	panierpb "verretech-microservices/panier/panierpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Commande struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        string           `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Panier    *panierpb.Panier `protobuf:"bytes,2,opt,name=panier,proto3" json:"panier,omitempty"`
	Timestamp int64            `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Statut    string           `protobuf:"bytes,4,opt,name=statut,proto3" json:"statut,omitempty"`
	Ref       string           `protobuf:"bytes,5,opt,name=ref,proto3" json:"ref,omitempty"`
}

func (x *Commande) Reset() {
	*x = Commande{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_commande_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Commande) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commande) ProtoMessage() {}

func (x *Commande) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commande_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commande.ProtoReflect.Descriptor instead.
func (*Commande) Descriptor() ([]byte, []int) {
	return file_proto_commande_proto_rawDescGZIP(), []int{0}
}

func (x *Commande) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Commande) GetPanier() *panierpb.Panier {
	if x != nil {
		return x.Panier
	}
	return nil
}

func (x *Commande) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Commande) GetStatut() string {
	if x != nil {
		return x.Statut
	}
	return ""
}

func (x *Commande) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

type PanierRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Panier *panierpb.Panier `protobuf:"bytes,1,opt,name=panier,proto3" json:"panier,omitempty"`
}

func (x *PanierRequest) Reset() {
	*x = PanierRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_commande_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PanierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PanierRequest) ProtoMessage() {}

func (x *PanierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commande_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PanierRequest.ProtoReflect.Descriptor instead.
func (*PanierRequest) Descriptor() ([]byte, []int) {
	return file_proto_commande_proto_rawDescGZIP(), []int{1}
}

func (x *PanierRequest) GetPanier() *panierpb.Panier {
	if x != nil {
		return x.Panier
	}
	return nil
}

type CommandeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commande *Commande `protobuf:"bytes,1,opt,name=commande,proto3" json:"commande,omitempty"`
}

func (x *CommandeRequest) Reset() {
	*x = CommandeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_commande_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandeRequest) ProtoMessage() {}

func (x *CommandeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commande_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandeRequest.ProtoReflect.Descriptor instead.
func (*CommandeRequest) Descriptor() ([]byte, []int) {
	return file_proto_commande_proto_rawDescGZIP(), []int{2}
}

func (x *CommandeRequest) GetCommande() *Commande {
	if x != nil {
		return x.Commande
	}
	return nil
}

type ConfirmRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommandeID string `protobuf:"bytes,1,opt,name=commandeID,proto3" json:"commandeID,omitempty"`
	UserID     string `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *ConfirmRequest) Reset() {
	*x = ConfirmRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_commande_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmRequest) ProtoMessage() {}

func (x *ConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commande_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmRequest.ProtoReflect.Descriptor instead.
func (*ConfirmRequest) Descriptor() ([]byte, []int) {
	return file_proto_commande_proto_rawDescGZIP(), []int{3}
}

func (x *ConfirmRequest) GetCommandeID() string {
	if x != nil {
		return x.CommandeID
	}
	return ""
}

func (x *ConfirmRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type CommandeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commande *Commande `protobuf:"bytes,1,opt,name=commande,proto3" json:"commande,omitempty"`
}

func (x *CommandeResponse) Reset() {
	*x = CommandeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_commande_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandeResponse) ProtoMessage() {}

func (x *CommandeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commande_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandeResponse.ProtoReflect.Descriptor instead.
func (*CommandeResponse) Descriptor() ([]byte, []int) {
	return file_proto_commande_proto_rawDescGZIP(), []int{4}
}

func (x *CommandeResponse) GetCommande() *Commande {
	if x != nil {
		return x.Commande
	}
	return nil
}

type CommandesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commandes []*Commande `protobuf:"bytes,1,rep,name=commandes,proto3" json:"commandes,omitempty"`
}

func (x *CommandesResponse) Reset() {
	*x = CommandesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_commande_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandesResponse) ProtoMessage() {}

func (x *CommandesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commande_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandesResponse.ProtoReflect.Descriptor instead.
func (*CommandesResponse) Descriptor() ([]byte, []int) {
	return file_proto_commande_proto_rawDescGZIP(), []int{5}
}

func (x *CommandesResponse) GetCommandes() []*Commande {
	if x != nil {
		return x.Commandes
	}
	return nil
}

type ByUtilisateurRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UtilisateurID string `protobuf:"bytes,1,opt,name=utilisateurID,proto3" json:"utilisateurID,omitempty"`
}

func (x *ByUtilisateurRequest) Reset() {
	*x = ByUtilisateurRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_commande_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ByUtilisateurRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ByUtilisateurRequest) ProtoMessage() {}

func (x *ByUtilisateurRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commande_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ByUtilisateurRequest.ProtoReflect.Descriptor instead.
func (*ByUtilisateurRequest) Descriptor() ([]byte, []int) {
	return file_proto_commande_proto_rawDescGZIP(), []int{6}
}

func (x *ByUtilisateurRequest) GetUtilisateurID() string {
	if x != nil {
		return x.UtilisateurID
	}
	return ""
}

var File_proto_commande_proto protoreflect.FileDescriptor

var file_proto_commande_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65,
	0x1a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x61, 0x6e, 0x69, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8a, 0x01, 0x0a, 0x08, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49,
	0x44, 0x12, 0x26, 0x0a, 0x06, 0x70, 0x61, 0x6e, 0x69, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x61, 0x6e, 0x69, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x6e, 0x69, 0x65,
	0x72, 0x52, 0x06, 0x70, 0x61, 0x6e, 0x69, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x72, 0x65, 0x66, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x65,
	0x66, 0x22, 0x37, 0x0a, 0x0d, 0x50, 0x61, 0x6e, 0x69, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x26, 0x0a, 0x06, 0x70, 0x61, 0x6e, 0x69, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x61, 0x6e, 0x69, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x6e, 0x69,
	0x65, 0x72, 0x52, 0x06, 0x70, 0x61, 0x6e, 0x69, 0x65, 0x72, 0x22, 0x41, 0x0a, 0x0f, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a,
	0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x65, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x22, 0x48, 0x0a,
	0x0e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x49, 0x44, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x42, 0x0a, 0x10, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x65, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x22, 0x45, 0x0a, 0x11, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x30, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x65, 0x73, 0x22, 0x3c, 0x0a, 0x14, 0x42, 0x79, 0x55, 0x74, 0x69, 0x6c, 0x69, 0x73, 0x61, 0x74,
	0x65, 0x75, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x75, 0x74,
	0x69, 0x6c, 0x69, 0x73, 0x61, 0x74, 0x65, 0x75, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x75, 0x74, 0x69, 0x6c, 0x69, 0x73, 0x61, 0x74, 0x65, 0x75, 0x72, 0x49, 0x44,
	0x32, 0xa2, 0x02, 0x0a, 0x0f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x65, 0x12, 0x3c, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x17, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x2e, 0x50, 0x61, 0x6e, 0x69, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3f, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x12, 0x18, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x06, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x12, 0x19, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x73, 0x12, 0x1e, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x65, 0x2e, 0x42, 0x79, 0x55, 0x74, 0x69, 0x6c, 0x69, 0x73, 0x61, 0x74, 0x65, 0x75,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2d, 0x5a, 0x2b, 0x76, 0x65, 0x72, 0x72, 0x65, 0x74, 0x65,
	0x63, 0x68, 0x2d, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_commande_proto_rawDescOnce sync.Once
	file_proto_commande_proto_rawDescData = file_proto_commande_proto_rawDesc
)

func file_proto_commande_proto_rawDescGZIP() []byte {
	file_proto_commande_proto_rawDescOnce.Do(func() {
		file_proto_commande_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_commande_proto_rawDescData)
	})
	return file_proto_commande_proto_rawDescData
}

var file_proto_commande_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_commande_proto_goTypes = []interface{}{
	(*Commande)(nil),             // 0: commande.Commande
	(*PanierRequest)(nil),        // 1: commande.PanierRequest
	(*CommandeRequest)(nil),      // 2: commande.CommandeRequest
	(*ConfirmRequest)(nil),       // 3: commande.ConfirmRequest
	(*CommandeResponse)(nil),     // 4: commande.CommandeResponse
	(*CommandesResponse)(nil),    // 5: commande.CommandesResponse
	(*ByUtilisateurRequest)(nil), // 6: commande.ByUtilisateurRequest
	(*panierpb.Panier)(nil),      // 7: panier.Panier
}
var file_proto_commande_proto_depIdxs = []int32{
	7, // 0: commande.Commande.panier:type_name -> panier.Panier
	7, // 1: commande.PanierRequest.panier:type_name -> panier.Panier
	0, // 2: commande.CommandeRequest.commande:type_name -> commande.Commande
	0, // 3: commande.CommandeResponse.commande:type_name -> commande.Commande
	0, // 4: commande.CommandesResponse.commandes:type_name -> commande.Commande
	1, // 5: commande.ServiceCommande.Valid:input_type -> commande.PanierRequest
	3, // 6: commande.ServiceCommande.Confirm:input_type -> commande.ConfirmRequest
	2, // 7: commande.ServiceCommande.Cancel:input_type -> commande.CommandeRequest
	6, // 8: commande.ServiceCommande.GetUserCommandes:input_type -> commande.ByUtilisateurRequest
	4, // 9: commande.ServiceCommande.Valid:output_type -> commande.CommandeResponse
	4, // 10: commande.ServiceCommande.Confirm:output_type -> commande.CommandeResponse
	4, // 11: commande.ServiceCommande.Cancel:output_type -> commande.CommandeResponse
	5, // 12: commande.ServiceCommande.GetUserCommandes:output_type -> commande.CommandesResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_commande_proto_init() }
func file_proto_commande_proto_init() {
	if File_proto_commande_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_commande_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Commande); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_commande_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PanierRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_commande_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_commande_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_commande_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_commande_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_commande_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ByUtilisateurRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_commande_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_commande_proto_goTypes,
		DependencyIndexes: file_proto_commande_proto_depIdxs,
		MessageInfos:      file_proto_commande_proto_msgTypes,
	}.Build()
	File_proto_commande_proto = out.File
	file_proto_commande_proto_rawDesc = nil
	file_proto_commande_proto_goTypes = nil
	file_proto_commande_proto_depIdxs = nil
}
