// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.15.6
// source: proto/commande.proto

package commandepb

import (
	panierpb "./panier/panierpb"
	utilisateurpb "./utilisateur/utilisateurpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Commande struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Panier    *panierpb.Panier `protobuf:"bytes,1,opt,name=panier,proto3" json:"panier,omitempty"`
	Timestamp int64            `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Statut    string           `protobuf:"bytes,3,opt,name=statut,proto3" json:"statut,omitempty"`
	Ref       string           `protobuf:"bytes,4,opt,name=ref,proto3" json:"ref,omitempty"`
}

func (x *Commande) Reset() {
	*x = Commande{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_commande_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Commande) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commande) ProtoMessage() {}

func (x *Commande) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commande_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commande.ProtoReflect.Descriptor instead.
func (*Commande) Descriptor() ([]byte, []int) {
	return file_proto_commande_proto_rawDescGZIP(), []int{0}
}

func (x *Commande) GetPanier() *panierpb.Panier {
	if x != nil {
		return x.Panier
	}
	return nil
}

func (x *Commande) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Commande) GetStatut() string {
	if x != nil {
		return x.Statut
	}
	return ""
}

func (x *Commande) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

type ListCommandes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commandes []*Commande `protobuf:"bytes,1,rep,name=commandes,proto3" json:"commandes,omitempty"`
}

func (x *ListCommandes) Reset() {
	*x = ListCommandes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_commande_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCommandes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommandes) ProtoMessage() {}

func (x *ListCommandes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commande_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommandes.ProtoReflect.Descriptor instead.
func (*ListCommandes) Descriptor() ([]byte, []int) {
	return file_proto_commande_proto_rawDescGZIP(), []int{1}
}

func (x *ListCommandes) GetCommandes() []*Commande {
	if x != nil {
		return x.Commandes
	}
	return nil
}

type CommandeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commande *Commande `protobuf:"bytes,1,opt,name=commande,proto3" json:"commande,omitempty"`
}

func (x *CommandeRequest) Reset() {
	*x = CommandeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_commande_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandeRequest) ProtoMessage() {}

func (x *CommandeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commande_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandeRequest.ProtoReflect.Descriptor instead.
func (*CommandeRequest) Descriptor() ([]byte, []int) {
	return file_proto_commande_proto_rawDescGZIP(), []int{2}
}

func (x *CommandeRequest) GetCommande() *Commande {
	if x != nil {
		return x.Commande
	}
	return nil
}

type CommandeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commande *Commande `protobuf:"bytes,1,opt,name=commande,proto3" json:"commande,omitempty"`
}

func (x *CommandeResponse) Reset() {
	*x = CommandeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_commande_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandeResponse) ProtoMessage() {}

func (x *CommandeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commande_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandeResponse.ProtoReflect.Descriptor instead.
func (*CommandeResponse) Descriptor() ([]byte, []int) {
	return file_proto_commande_proto_rawDescGZIP(), []int{3}
}

func (x *CommandeResponse) GetCommande() *Commande {
	if x != nil {
		return x.Commande
	}
	return nil
}

type LastCommandesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LastCommandesRequest) Reset() {
	*x = LastCommandesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_commande_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LastCommandesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastCommandesRequest) ProtoMessage() {}

func (x *LastCommandesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commande_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastCommandesRequest.ProtoReflect.Descriptor instead.
func (*LastCommandesRequest) Descriptor() ([]byte, []int) {
	return file_proto_commande_proto_rawDescGZIP(), []int{4}
}

type CommandesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListCommandes *ListCommandes `protobuf:"bytes,1,opt,name=ListCommandes,proto3" json:"ListCommandes,omitempty"`
}

func (x *CommandesResponse) Reset() {
	*x = CommandesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_commande_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandesResponse) ProtoMessage() {}

func (x *CommandesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commande_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandesResponse.ProtoReflect.Descriptor instead.
func (*CommandesResponse) Descriptor() ([]byte, []int) {
	return file_proto_commande_proto_rawDescGZIP(), []int{5}
}

func (x *CommandesResponse) GetListCommandes() *ListCommandes {
	if x != nil {
		return x.ListCommandes
	}
	return nil
}

type ByUtilisateurRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Utilisateur *utilisateurpb.Utilisateur `protobuf:"bytes,1,opt,name=utilisateur,proto3" json:"utilisateur,omitempty"`
}

func (x *ByUtilisateurRequest) Reset() {
	*x = ByUtilisateurRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_commande_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ByUtilisateurRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ByUtilisateurRequest) ProtoMessage() {}

func (x *ByUtilisateurRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commande_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ByUtilisateurRequest.ProtoReflect.Descriptor instead.
func (*ByUtilisateurRequest) Descriptor() ([]byte, []int) {
	return file_proto_commande_proto_rawDescGZIP(), []int{6}
}

func (x *ByUtilisateurRequest) GetUtilisateur() *utilisateurpb.Utilisateur {
	if x != nil {
		return x.Utilisateur
	}
	return nil
}

var File_proto_commande_proto protoreflect.FileDescriptor

var file_proto_commande_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65,
	0x1a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x61, 0x6e, 0x69, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x74, 0x69, 0x6c,
	0x69, 0x73, 0x61, 0x74, 0x65, 0x75, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7a, 0x0a,
	0x08, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x70, 0x61, 0x6e,
	0x69, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x61, 0x6e, 0x69,
	0x65, 0x72, 0x2e, 0x50, 0x61, 0x6e, 0x69, 0x65, 0x72, 0x52, 0x06, 0x70, 0x61, 0x6e, 0x69, 0x65,
	0x72, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x66, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x65, 0x66, 0x22, 0x41, 0x0a, 0x0d, 0x4c, 0x69, 0x73,
	0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x73, 0x12, 0x30, 0x0a, 0x09, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x65, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x73, 0x22, 0x41, 0x0a, 0x0f,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x2e, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x65, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x22,
	0x42, 0x0a, 0x10, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x65, 0x22, 0x16, 0x0a, 0x14, 0x4c, 0x61, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x52, 0x0a, 0x11, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3d, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x73,
	0x52, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x73, 0x22,
	0x52, 0x0a, 0x14, 0x42, 0x79, 0x55, 0x74, 0x69, 0x6c, 0x69, 0x73, 0x61, 0x74, 0x65, 0x75, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x0b, 0x75, 0x74, 0x69, 0x6c, 0x69,
	0x73, 0x61, 0x74, 0x65, 0x75, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x75,
	0x74, 0x69, 0x6c, 0x69, 0x73, 0x61, 0x74, 0x65, 0x75, 0x72, 0x2e, 0x55, 0x74, 0x69, 0x6c, 0x69,
	0x73, 0x61, 0x74, 0x65, 0x75, 0x72, 0x52, 0x0b, 0x75, 0x74, 0x69, 0x6c, 0x69, 0x73, 0x61, 0x74,
	0x65, 0x75, 0x72, 0x32, 0xc7, 0x02, 0x0a, 0x0f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x12, 0x49, 0x0a, 0x10, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x12, 0x19, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x47, 0x0a, 0x0e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x65, 0x12, 0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x2e,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1a, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x10, 0x47,
	0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x73, 0x12,
	0x1e, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x2e, 0x4c, 0x61, 0x73, 0x74, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1b, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x10,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x73,
	0x12, 0x1e, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x2e, 0x42, 0x79, 0x55, 0x74,
	0x69, 0x6c, 0x69, 0x73, 0x61, 0x74, 0x65, 0x75, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1b, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x17, 0x5a,
	0x15, 0x2e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_commande_proto_rawDescOnce sync.Once
	file_proto_commande_proto_rawDescData = file_proto_commande_proto_rawDesc
)

func file_proto_commande_proto_rawDescGZIP() []byte {
	file_proto_commande_proto_rawDescOnce.Do(func() {
		file_proto_commande_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_commande_proto_rawDescData)
	})
	return file_proto_commande_proto_rawDescData
}

var file_proto_commande_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_commande_proto_goTypes = []interface{}{
	(*Commande)(nil),                  // 0: commande.Commande
	(*ListCommandes)(nil),             // 1: commande.ListCommandes
	(*CommandeRequest)(nil),           // 2: commande.CommandeRequest
	(*CommandeResponse)(nil),          // 3: commande.CommandeResponse
	(*LastCommandesRequest)(nil),      // 4: commande.LastCommandesRequest
	(*CommandesResponse)(nil),         // 5: commande.CommandesResponse
	(*ByUtilisateurRequest)(nil),      // 6: commande.ByUtilisateurRequest
	(*panierpb.Panier)(nil),           // 7: panier.Panier
	(*utilisateurpb.Utilisateur)(nil), // 8: utilisateur.Utilisateur
}
var file_proto_commande_proto_depIdxs = []int32{
	7,  // 0: commande.Commande.panier:type_name -> panier.Panier
	0,  // 1: commande.ListCommandes.commandes:type_name -> commande.Commande
	0,  // 2: commande.CommandeRequest.commande:type_name -> commande.Commande
	0,  // 3: commande.CommandeResponse.commande:type_name -> commande.Commande
	1,  // 4: commande.CommandesResponse.ListCommandes:type_name -> commande.ListCommandes
	8,  // 5: commande.ByUtilisateurRequest.utilisateur:type_name -> utilisateur.Utilisateur
	2,  // 6: commande.ServiceCommande.ValidateCommande:input_type -> commande.CommandeRequest
	2,  // 7: commande.ServiceCommande.SubmitCommande:input_type -> commande.CommandeRequest
	4,  // 8: commande.ServiceCommande.GetLastCommandes:input_type -> commande.LastCommandesRequest
	6,  // 9: commande.ServiceCommande.GetUserCommandes:input_type -> commande.ByUtilisateurRequest
	3,  // 10: commande.ServiceCommande.ValidateCommande:output_type -> commande.CommandeResponse
	3,  // 11: commande.ServiceCommande.SubmitCommande:output_type -> commande.CommandeResponse
	5,  // 12: commande.ServiceCommande.GetLastCommandes:output_type -> commande.CommandesResponse
	5,  // 13: commande.ServiceCommande.GetUserCommandes:output_type -> commande.CommandesResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_commande_proto_init() }
func file_proto_commande_proto_init() {
	if File_proto_commande_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_commande_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Commande); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_commande_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCommandes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_commande_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_commande_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_commande_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LastCommandesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_commande_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_commande_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ByUtilisateurRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_commande_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_commande_proto_goTypes,
		DependencyIndexes: file_proto_commande_proto_depIdxs,
		MessageInfos:      file_proto_commande_proto_msgTypes,
	}.Build()
	File_proto_commande_proto = out.File
	file_proto_commande_proto_rawDesc = nil
	file_proto_commande_proto_goTypes = nil
	file_proto_commande_proto_depIdxs = nil
}
