// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: proto/panier.proto

package panierpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	produitpb "verretech-microservices/produit/produitpb"
	utilisateurpb "verretech-microservices/utilisateur/utilisateurpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Article struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Produit *produitpb.Produit `protobuf:"bytes,1,opt,name=produit,proto3" json:"produit,omitempty"`
	Qte     int32              `protobuf:"varint,2,opt,name=qte,proto3" json:"qte,omitempty"`
}

func (x *Article) Reset() {
	*x = Article{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_panier_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_proto_panier_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_proto_panier_proto_rawDescGZIP(), []int{0}
}

func (x *Article) GetProduit() *produitpb.Produit {
	if x != nil {
		return x.Produit
	}
	return nil
}

func (x *Article) GetQte() int32 {
	if x != nil {
		return x.Qte
	}
	return 0
}

type Panier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Utilisateur *utilisateurpb.Utilisateur `protobuf:"bytes,1,opt,name=utilisateur,proto3" json:"utilisateur,omitempty"`
	Article     []*Article                 `protobuf:"bytes,2,rep,name=article,proto3" json:"article,omitempty"`
}

func (x *Panier) Reset() {
	*x = Panier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_panier_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Panier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Panier) ProtoMessage() {}

func (x *Panier) ProtoReflect() protoreflect.Message {
	mi := &file_proto_panier_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Panier.ProtoReflect.Descriptor instead.
func (*Panier) Descriptor() ([]byte, []int) {
	return file_proto_panier_proto_rawDescGZIP(), []int{1}
}

func (x *Panier) GetUtilisateur() *utilisateurpb.Utilisateur {
	if x != nil {
		return x.Utilisateur
	}
	return nil
}

func (x *Panier) GetArticle() []*Article {
	if x != nil {
		return x.Article
	}
	return nil
}

type PanierRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Panier *Panier `protobuf:"bytes,1,opt,name=panier,proto3" json:"panier,omitempty"`
}

func (x *PanierRequest) Reset() {
	*x = PanierRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_panier_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PanierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PanierRequest) ProtoMessage() {}

func (x *PanierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_panier_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PanierRequest.ProtoReflect.Descriptor instead.
func (*PanierRequest) Descriptor() ([]byte, []int) {
	return file_proto_panier_proto_rawDescGZIP(), []int{2}
}

func (x *PanierRequest) GetPanier() *Panier {
	if x != nil {
		return x.Panier
	}
	return nil
}

type ByUtilisateurRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Utilisateur *utilisateurpb.Utilisateur `protobuf:"bytes,1,opt,name=utilisateur,proto3" json:"utilisateur,omitempty"`
}

func (x *ByUtilisateurRequest) Reset() {
	*x = ByUtilisateurRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_panier_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ByUtilisateurRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ByUtilisateurRequest) ProtoMessage() {}

func (x *ByUtilisateurRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_panier_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ByUtilisateurRequest.ProtoReflect.Descriptor instead.
func (*ByUtilisateurRequest) Descriptor() ([]byte, []int) {
	return file_proto_panier_proto_rawDescGZIP(), []int{3}
}

func (x *ByUtilisateurRequest) GetUtilisateur() *utilisateurpb.Utilisateur {
	if x != nil {
		return x.Utilisateur
	}
	return nil
}

type PanierResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Panier *Panier `protobuf:"bytes,1,opt,name=panier,proto3" json:"panier,omitempty"`
}

func (x *PanierResponse) Reset() {
	*x = PanierResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_panier_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PanierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PanierResponse) ProtoMessage() {}

func (x *PanierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_panier_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PanierResponse.ProtoReflect.Descriptor instead.
func (*PanierResponse) Descriptor() ([]byte, []int) {
	return file_proto_panier_proto_rawDescGZIP(), []int{4}
}

func (x *PanierResponse) GetPanier() *Panier {
	if x != nil {
		return x.Panier
	}
	return nil
}

var File_proto_panier_proto protoreflect.FileDescriptor

var file_proto_panier_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x61, 0x6e, 0x69, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x61, 0x6e, 0x69, 0x65, 0x72, 0x1a, 0x17, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x69, 0x73, 0x61, 0x74, 0x65, 0x75, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x47, 0x0a, 0x07, 0x41, 0x72,
	0x74, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x2a, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x69, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x69, 0x74,
	0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x69, 0x74, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x69,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x71, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x71, 0x74, 0x65, 0x22, 0x6f, 0x0a, 0x06, 0x50, 0x61, 0x6e, 0x69, 0x65, 0x72, 0x12, 0x3a, 0x0a,
	0x0b, 0x75, 0x74, 0x69, 0x6c, 0x69, 0x73, 0x61, 0x74, 0x65, 0x75, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x69, 0x73, 0x61, 0x74, 0x65, 0x75, 0x72,
	0x2e, 0x55, 0x74, 0x69, 0x6c, 0x69, 0x73, 0x61, 0x74, 0x65, 0x75, 0x72, 0x52, 0x0b, 0x75, 0x74,
	0x69, 0x6c, 0x69, 0x73, 0x61, 0x74, 0x65, 0x75, 0x72, 0x12, 0x29, 0x0a, 0x07, 0x61, 0x72, 0x74,
	0x69, 0x63, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x61, 0x6e,
	0x69, 0x65, 0x72, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x07, 0x61, 0x72, 0x74,
	0x69, 0x63, 0x6c, 0x65, 0x22, 0x37, 0x0a, 0x0d, 0x50, 0x61, 0x6e, 0x69, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x06, 0x70, 0x61, 0x6e, 0x69, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x61, 0x6e, 0x69, 0x65, 0x72, 0x2e, 0x50,
	0x61, 0x6e, 0x69, 0x65, 0x72, 0x52, 0x06, 0x70, 0x61, 0x6e, 0x69, 0x65, 0x72, 0x22, 0x52, 0x0a,
	0x14, 0x42, 0x79, 0x55, 0x74, 0x69, 0x6c, 0x69, 0x73, 0x61, 0x74, 0x65, 0x75, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x0b, 0x75, 0x74, 0x69, 0x6c, 0x69, 0x73, 0x61,
	0x74, 0x65, 0x75, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x75, 0x74, 0x69,
	0x6c, 0x69, 0x73, 0x61, 0x74, 0x65, 0x75, 0x72, 0x2e, 0x55, 0x74, 0x69, 0x6c, 0x69, 0x73, 0x61,
	0x74, 0x65, 0x75, 0x72, 0x52, 0x0b, 0x75, 0x74, 0x69, 0x6c, 0x69, 0x73, 0x61, 0x74, 0x65, 0x75,
	0x72, 0x22, 0x38, 0x0a, 0x0e, 0x50, 0x61, 0x6e, 0x69, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x70, 0x61, 0x6e, 0x69, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x61, 0x6e, 0x69, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x6e,
	0x69, 0x65, 0x72, 0x52, 0x06, 0x70, 0x61, 0x6e, 0x69, 0x65, 0x72, 0x32, 0x91, 0x01, 0x0a, 0x0d,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x61, 0x6e, 0x69, 0x65, 0x72, 0x12, 0x3d, 0x0a,
	0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x6e, 0x69, 0x65, 0x72, 0x12, 0x15, 0x2e,
	0x70, 0x61, 0x6e, 0x69, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x6e, 0x69, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x61, 0x6e, 0x69, 0x65, 0x72, 0x2e, 0x50, 0x61,
	0x6e, 0x69, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x09,
	0x47, 0x65, 0x74, 0x50, 0x61, 0x6e, 0x69, 0x65, 0x72, 0x12, 0x1c, 0x2e, 0x70, 0x61, 0x6e, 0x69,
	0x65, 0x72, 0x2e, 0x42, 0x79, 0x55, 0x74, 0x69, 0x6c, 0x69, 0x73, 0x61, 0x74, 0x65, 0x75, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x61, 0x6e, 0x69, 0x65, 0x72,
	0x2e, 0x50, 0x61, 0x6e, 0x69, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x29, 0x5a, 0x27, 0x76, 0x65, 0x72, 0x72, 0x65, 0x74, 0x65, 0x63, 0x68, 0x2d, 0x6d, 0x69, 0x63,
	0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x61, 0x6e, 0x69, 0x65,
	0x72, 0x2f, 0x70, 0x61, 0x6e, 0x69, 0x65, 0x72, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_panier_proto_rawDescOnce sync.Once
	file_proto_panier_proto_rawDescData = file_proto_panier_proto_rawDesc
)

func file_proto_panier_proto_rawDescGZIP() []byte {
	file_proto_panier_proto_rawDescOnce.Do(func() {
		file_proto_panier_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_panier_proto_rawDescData)
	})
	return file_proto_panier_proto_rawDescData
}

var file_proto_panier_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_panier_proto_goTypes = []interface{}{
	(*Article)(nil),                   // 0: panier.Article
	(*Panier)(nil),                    // 1: panier.Panier
	(*PanierRequest)(nil),             // 2: panier.PanierRequest
	(*ByUtilisateurRequest)(nil),      // 3: panier.ByUtilisateurRequest
	(*PanierResponse)(nil),            // 4: panier.PanierResponse
	(*produitpb.Produit)(nil),         // 5: produit.Produit
	(*utilisateurpb.Utilisateur)(nil), // 6: utilisateur.Utilisateur
}
var file_proto_panier_proto_depIdxs = []int32{
	5, // 0: panier.Article.produit:type_name -> produit.Produit
	6, // 1: panier.Panier.utilisateur:type_name -> utilisateur.Utilisateur
	0, // 2: panier.Panier.article:type_name -> panier.Article
	1, // 3: panier.PanierRequest.panier:type_name -> panier.Panier
	6, // 4: panier.ByUtilisateurRequest.utilisateur:type_name -> utilisateur.Utilisateur
	1, // 5: panier.PanierResponse.panier:type_name -> panier.Panier
	2, // 6: panier.ServicePanier.UpdatePanier:input_type -> panier.PanierRequest
	3, // 7: panier.ServicePanier.GetPanier:input_type -> panier.ByUtilisateurRequest
	4, // 8: panier.ServicePanier.UpdatePanier:output_type -> panier.PanierResponse
	4, // 9: panier.ServicePanier.GetPanier:output_type -> panier.PanierResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_panier_proto_init() }
func file_proto_panier_proto_init() {
	if File_proto_panier_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_panier_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Article); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_panier_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Panier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_panier_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PanierRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_panier_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ByUtilisateurRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_panier_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PanierResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_panier_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_panier_proto_goTypes,
		DependencyIndexes: file_proto_panier_proto_depIdxs,
		MessageInfos:      file_proto_panier_proto_msgTypes,
	}.Build()
	File_proto_panier_proto = out.File
	file_proto_panier_proto_rawDesc = nil
	file_proto_panier_proto_goTypes = nil
	file_proto_panier_proto_depIdxs = nil
}
