version: '3.0'

services:
  produit:
    build:
      context: .
      dockerfile: ./produit/install/Dockerfile
  utilisateur:
    build:
      context: .
      dockerfile: ./utilisateur/install/Dockerfile
